//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRecritmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int Jobid { get; set; }
        public string Designation { get; set; }
        public string Company { get; set; }
        public string ComapnyName { get; set; }
        public string Salary { get; set; }
    }
}
