//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRecritmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSeeker
    {
        public string Name { get; set; }
        public string Password { get; set; }
        public string Emailid { get; set; }
        public string MobileNo { get; set; }
        public string Location { get; set; }
        public byte[] photo { get; set; }
        public string Position { get; set; }
        public string Experience { get; set; }
        public string PreferredJobLocation { get; set; }
        public string Skills { get; set; }
        public Nullable<System.DateTime> Dateofapplication { get; set; }
        public byte[] Resume { get; set; }
        public string Status { get; set; }
    }
}
